### ISSUE TITLE
openDialog is not defined.

### ISSUE THREAD

**Issue by vivekparekh8** [jacklam718/react-native-dialog-component#1]

**Comment by jacklam718** [comment]
@vivekparekh8 
Sorry to reply you so late 😬
I've tried and it seems to work properly.
If you can show me your code that would be better.

**Comment by vivekparekh8** [comment]
`
import DialogComponent, { SlideAnimation } from 'react-native-dialog-component'
import React, { Component, PropTypes } from 'react'

class ModalWrapper extends Component {
  constructor(props) {
    super(props)
  }
  componentWillMount() {
    const { showModal } = this.props
    this.dialogComponent.openDialog()
  }

  render() {
    const { visible } = this.props
    return (
      <DialogComponent
        onClosed={() => { this.setState({ modalVisible : false }) }}
        ref={(dialogComponent) => { this.dialogComponent = dialogComponent; }}
        open={visible}
        dialogAnimation = { new SlideAnimation({ slideFrom: 'bottom' }) }
      />
    )
  }
}

ModalWrapper.propTypes = {
  showModal: PropTypes.boolean
}

export default ModalWrapper
`

**Comment by vivekparekh8** [comment]
Don't know how to open and close it.

**Comment by jacklam718** [comment]
@vivekparekh8 

If you want open the dialog when your component mounted.

##### you can do this:
```javascript
class ModalWrapper extends Component {
  componentDidMount() {
    this.dialogComponent.openDialog()
  }

  render() {
    return (
      <DialogComponent
        ref={(dialogComponent) => { this.dialogComponent = dialogComponent; }}
        dialogAnimation={ new SlideAnimation({ slideFrom: 'bottom' }) }
      />
    )
  }
}
```
##### OR
```javascript
class ModalWrapper extends Component {
  constructor(props) {
    super(props)

    this.state = {
      dialogOpen: true,
    };
    
    this.openDialog = this.openDialog.bind(this)
    this.closeDialog = this.closeDialog.bind(this)
  }

  openDialog() {
    this.setState({ dialogOpen: true });
  }
  
  closeDialog() {
    this.setState({ dialogOpen: false });
  }

  render() {
    const { dialogOpen } = this.state;
    return (
      <DialogComponent
        open={dialogOpen}
        dialogAnimation={ new SlideAnimation({ slideFrom: 'bottom' }) }
      />
    )
  }
}
```

**Comment by vivekparekh8** [comment]
@jacklam718 ```<View style={[modalBackgroundStyle, modalViewStyle]}>
            <InnerView {...this.props} />
          </View>```
Iwant above to be passed inside Dialog from other component. Can you advise?
Thanks

**Comment by vivekparekh8** [comment]
I am still unable to show dialog using your method

**Comment by vivekparekh8** [comment]
I no longer use this. thanks.
