### ISSUE TITLE
Postition of the Dialog & using state or class variable

### ISSUE THREAD

**Issue by shekharskamble** [jacklam718/react-native-dialog-component#11]
Hi Jack,

Great library, I want to achieve something like this

<img width="158" alt="popup" src="https://user-images.githubusercontent.com/8002785/33355891-6ece6d02-d4f4-11e7-91f5-4b3918d80ce4.png">

How can I position the dialog to the bottom of the screen? Also tried to use state & class variable to display message but it doesn't work :(

My Code: 

              <DialogComponent
                  title="Edit"
                  titleAlign="left"
                  dialogStyle={{borderTopLeftRadius:20, borderTopRightRadius:20}}
                  titleTextStyle={{fontSize:14, fontWeight:'bold', color:'#000'}}
                  dialogAnimation = { new SlideAnimation({ slideFrom: 'bottom' }) }
                  dialogButton= {<DialogButton text="Close" align='right'/>}
                  height={300}
                  ref={(dialogComponent) => { this.dialogComponent = dialogComponent; }}>
                  <DialogContent>
                    <View>
                      <Text>{this.message}</Text> // tried to use state & class variable but doesnt work
                    </View>
                  </DialogContent>
                </DialogComponent>

Please help.

**Comment by jacklam718** [comment]
@shekharskamble 
1.  set dialog as `position: 'absolute' and bottom: 0` via `dialogStyle` prop
2. You might need to implement your own animation to fit your needs (I'm not so sure)
3. About using `state or class variable`. It's not related to this Library. it mostly about React. You could study React's documents.

```javascript
const slideAnimation = new SlideAnimation({ slideFrom: 'bottom' }) 
<DialogComponent
  title="Edit"
  titleAlign="left"
  dialogStyle={{borderTopLeftRadius:20, borderTopRightRadius:20, position: 'absolute', bottom: 0}}
  titleTextStyle={{fontSize:14, fontWeight:'bold', color:'#000'}}
  dialogAnimation={slideAnimation}
  dialogButton= {<DialogButton text="Close" align='right'/>}
  height={300}
  ref={(dialogComponent) => { this.dialogComponent = dialogComponent; }}
>
  <DialogContent>
    <View>
      <Text>{this.message}</Text> // tried to user state & class variable but doesnt work
    </View>
  </DialogContent>
</DialogComponent>
```

**Comment by shekharskamble** [comment]
Thanks a lot for speedy reply, I tried to use state variable & class variable inside DialogContent but it doesn't work am I doing something wrong?

**Comment by jacklam718** [comment]
You should use component state

**Comment by shekharskamble** [comment]
Thank you for your reply & sorry to bother you so much, I did try     <Text>{this.state.message}</Text> inside DialogContent  but it doesn't work. By Component state you mean dialog components state?

**Comment by jacklam718** [comment]
Ok, what do you mean by doesn't work? nothing display?

**Comment by shekharskamble** [comment]
Yes it doesn't display the dialog but the overlay gets displayed....

**Comment by shekharskamble** [comment]
setState asynchronous issue.... resolved it by adding callback function

**Comment by jacklam718** [comment]
Nice!

**Comment by faizan992** [comment]
Hi @shekharskamble , i am also facing the same problem, did you find any solution ?

**Comment by shekharskamble** [comment]
@faizan992 when you setState message in that callback open the dialog
