### ISSUE TITLE
Wrap dialog content?

### ISSUE THREAD

**Issue by Knight704** [jacklam718/react-native-dialog-component#5]
Are there any way not to provide height to dialog, but make it depend on it's content?
i.e dialog could contain text with dynamic length and should look smaller for smaller length, higher for higher length accordingly

**Comment by jacklam718** [comment]
@Knight704 
Just set null in **width** and **height** props
```javascript
<DialogComponent
  width={null}
  height={null}
  ref={(dialogComponent) => {
    this.dialogComponent = dialogComponent;
  }}
>
  <View>
    <Text>
      React Native Dialog Component
    </Text>
  </View>
</DialogComponent>
```

**Comment by Knight704** [comment]
@jacklam718 thank you, that works. Although, in fact it should be null by default (in my opinion)

**Comment by jacklam718** [comment]
@Knight704 Will consider about that
