### ISSUE TITLE
Dialog is not centered align to screen

### ISSUE THREAD

**Issue by shekharskamble** [jacklam718/react-native-dialog-component#7]
I am using a ScrollView as a main container and inside that I am using a dialog but it looks like this.

![screenshot_20171009-082548](https://user-images.githubusercontent.com/8002785/31325378-d3f2e812-acee-11e7-8d20-e522ae60f1f9.png)

How can I fix this? Am I missing something?

**Comment by jacklam718** [comment]
@shekharskamble Can you show me your code?

**Comment by shekharskamble** [comment]
I resolved it using the normal View instead of scrollview thanks
