### ISSUE TITLE
Error when using Dialog Component

### ISSUE THREAD

**Issue by bhatti-waqas** [jacklam718/react-native-dialog-component#8]
![simulator screen shot 16-oct-2017 4 16 32 pm](https://user-images.githubusercontent.com/9653275/31705307-59ece48e-b3fe-11e7-8f12-97db57c9e1b5.png)

**Comment by pyros2097** [comment]
@bhatti-waqas  Please add more description in the issue. Anyways the latest version of react-native has changed the paths to some files which breaks one dependency. I've sent a pull request to fix this. One its merged we just need to update the version.
https://github.com/magicismight/react-native-root-siblings/pull/19

**Comment by jacklam718** [comment]
@pyros2097 Thanks

**Comment by jacklam718** [comment]
@bhatti-waqas This should be fixed by @pyros2097's PR https://github.com/jacklam718/react-native-dialog-component/pull/10 @bhatti-waqas You could try install the latest version.
